apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] <= 68.5
    failureLimit: 3
    provider:
      prometheus:
        address: https://prometheus.aoa.oes.opsmx.org
        query: |
          sum(rate(http_server_requests_seconds_bucket{kubernetes_pod_name=~".*"}[5m]))
